<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="safety_offset" value="0.02"/>

  <xacro:include filename="$(find schunk_lwa4p)/only_effort_controller/common_effort.xacro" />
  <xacro:include filename="$(find schunk_description)/urdf/lwa4p/lwa4p.gazebo.xacro" />
  <xacro:include filename="$(find schunk_lwa4p)/only_effort_controller/lwa4p_effort.transmission.xacro" />

  <xacro:macro name="schunk_lwa4p" params="parent name *origin has_podest">

    <xacro:if value="${has_podest}">
      <!-- joint between base_link and lwa4p_extended_connector_link -->
      <joint name="${name}_podest_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_podest_link"/>
      </joint>
      <link name="${name}_podest_link">
        <xacro:default_inertial/>
        <visual>
          <origin xyz="0 0 0" rpy="0 ${M_PI} 0" />
          <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_base_link.stl" />
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="0 ${M_PI} 0" />
          <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_base_link.stl" />
          </geometry>
        </collision>
      </link>

      <joint name="${name}_base_joint" type="fixed">
        <origin xyz="0 0 0.10" rpy="0 0 0" />
        <parent link="${name}_podest_link"/>
        <child link="${name}_base_link"/>
      </joint>
    </xacro:if>

    <xacro:unless value="${has_podest}">
      <!-- joint between base_link and lwa4p_extended_connector_link -->
      <joint name="${name}_base_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_base_link"/>
      </joint>
    </xacro:unless>

    <link name="${name}_base_link">
      <xacro:default_inertial/>
    </link>

    <!-- joint between arm_0_link and arm_1_link -->
    <joint name="${name}_1_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${name}_base_link"/>
      <child link="${name}_1_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="370" velocity="0.2" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}"/>
      <!--safety_controller k_position="20" k_velocity="50" soft_lower_limit="${-6.28 + 0.01}" soft_upper_limit="${6.28 - 0.01}" /-->
    </joint>

    <link name="${name}_1_link">
      <!--xacro:default_inertial/-->

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.29364"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>


      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_1_link.stl" />
        </geometry>
        <material name="Schunk/Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_1_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_1_link and arm_2_link -->
    <joint name="${name}_2_joint" type="revolute">
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <parent link="${name}_1_link"/>
      <child link="${name}_2_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="370" velocity="0.2" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}"/>
      <!--safety_controller k_position="20" k_velocity="50" soft_lower_limit="${-2.09 + 0.01}" soft_upper_limit="${2.09 - 0.01}" /-->
    </joint>

    <link name="${name}_2_link">
      <!--xacro:default_inertial/-->

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.68311"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>


      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_2_link.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_2_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_2_link and arm_3_link -->
    <joint name="${name}_3_joint" type="revolute">
      <origin xyz="0 0.350 0" rpy="0 3.14159 0"/>
      <parent link="${name}_2_link"/>
      <child link="${name}_3_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="176" velocity="1.26" lower="${-2.714 + safety_offset}" upper="${2.714 - safety_offset}"/>
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-6.28 + 0.01}" soft_upper_limit="${6.28 - 0.01}" /-->
    </joint>

    <link name="${name}_3_link">
      <!--xacro:default_inertial/-->

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.1"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>


      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_3_link.stl" />
        </geometry>
        <material name="Schunk/Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_3_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_3_link and arm_4_link -->
    <joint name="${name}_4_joint" type="revolute">
      <origin xyz="0 0 0" rpy="-1.5708 3.14159 0" />
      <parent link="${name}_3_link"/>
      <child link="${name}_4_link"/>
      <axis xyz="0 0 1" />
      <limit effort="176" velocity="1.26" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}"/>
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.09 + 0.01}" soft_upper_limit="${2.09 - 0.01}" /-->
    </joint>

    <link name="${name}_4_link">
      <!--xacro:default_inertial/-->

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.68311"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>


      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_4_link.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_4_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_4_link and arm_5_link -->
    <joint name="${name}_5_joint" type="revolute">
      <origin xyz="0 0.005263 0.305" rpy="1.5708 0 3.14159" />
      <parent link="${name}_4_link"/>
      <child link="${name}_5_link"/>
      <axis xyz="0 0 1" />
      <limit effort="41.6" velocity="1.26" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}" />
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-6.28 + 0.01}" soft_upper_limit="${6.28 - 0.01}" /-->
    </joint>

    <link name="${name}_5_link">
      <!--xacro:default_inertial/-->

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.807"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>


      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_5_link.stl" />
        </geometry>
        <material name="Schunk/Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_5_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_5_link and arm_6_link -->
    <joint name="${name}_6_joint" type="revolute">
      <origin xyz="0 0 0" rpy="-1.5708 0 0" />
      <parent link="${name}_5_link"/>
      <child link="${name}_6_link"/>
      <axis xyz="0 0 1" />
      <limit effort="20.1" velocity="1.26" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}" />
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.09 + 0.01}" soft_upper_limit="${2.09 - 0.01}" /-->
    </joint>

    <link name="${name}_6_link">
      <!--xacro:default_inertial/-->

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.819"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>


      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_6_link.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_6_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_6_link and Gripper -->
    <joint name="${name}_gripper_base" type="fixed">
      <origin xyz="0 0 0.09" rpy="1.5708 0 0" />
      <parent link="${name}_6_link" />
      <child link="${name}_gripper_link" />
    </joint>

    <link name="${name}_gripper_link">
      <xacro:default_inertial/>

      <visual>
        <origin xyz="-0.032 -0.005 -0.032" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/gripper_base.STL" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Schunk/Blue" />
      </visual>

      <collision>
        <origin xyz="-0.032 -0.005 -0.032" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/gripper_base.STL" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>

    <!-- joint between gripper_base and finger1 -->
    <joint name="${name}_finger1" type="prismatic">
      <origin xyz="0 0.111 -0.01" rpy="-1.5708 0 0" />
      <parent link="${name}_gripper_link" />
      <child link="${name}_finger1_link" />
      <axis xyz="0 1 0" />
      <limit effort="1" velocity="1.26" lower="${-0.01}" upper="${0}" />
    </joint>

    <link name="${name}_finger1_link">
      <xacro:default_inertial/>

      <visual>
        <origin xyz="-0.008 0.003 0.013" rpy="-1.5708 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/finger1.STL" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>

      <collision>
        <origin xyz="-0.008 0.003 0.013" rpy="-1.5708 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/finger1.STL" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>

    <!-- joint between gripper_base and finger2 -->
    <joint name="${name}_finger2" type="prismatic">
      <origin xyz="0 0.111 0.01" rpy="-1.5708 0 0" />
      <parent link="${name}_gripper_link" />
      <child link="${name}_finger2_link" />
      <axis xyz="0 1 0" />
      <limit effort="1" velocity="1.26" lower="${0}" upper="${0.01}" />
    </joint>

    <link name="${name}_finger2_link">
      <xacro:default_inertial/>

      <visual>
        <origin xyz="-0.008 -0.012 0.013" rpy="-1.5708 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/finger1.STL" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>

      <collision>
        <origin xyz="-0.008 -0.012 0.013" rpy="-1.5708 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/finger1.STL" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>


    <!-- extensions -->
    <xacro:schunk_lwa4p_gazebo name="${name}" />
    <xacro:schunk_lwa4p_transmission name="${name}" />

    <!-- ros_control plugin -->

    <gazebo>
      <plugin name="ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/${name}</robotNamespace>
        <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        <legacyModeNS>true</legacyModeNS>
      </plugin>
    </gazebo>

  </xacro:macro>



</robot>
